name: Build and Push Docker Image of operator

on: [push]
  # workflow_run:
  #   workflows: ["Tests"]
  #   types:
  #     - completed
  # push:
  #   tags:
  #       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker config with auth
        run: |
          mkdir -p ~/.docker
          echo '${{ secrets.DOCKER_AUTH_CONFIG }}' > ~/.docker/config.json

      - name: Push docker
        run: |
          docker build -t docker-picodata.binary.picodata.io/tarantool-operator::${{ github.ref_name }} .
          docker --config ~/.docker/ push docker-picodata.binary.picodata.io/tarantool-operator::${{ github.ref_name }}

      - name: Delete docker auth config
        run: rm -rf ~/.docker/config.json  # Clean up Docker auth credentials
